const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
const PORT = process.env.PORT || 3001;
app.use(cors());
app.use(express.json());
const tasksRouter = require('./routes/tasks');
app.use('/api/tasks', tasksRouter);
app.listen(PORT, () => { console.log(`Servidor escuchando en el puerto ${PORT}`); });